# Generated by Django 5.1.7 on 2025-03-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='letters/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='sounds/letters/')),
            ],
        ),
    ]
